name: CI 
on:
  pull_request:
    branches: [main] 
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Clone code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: NODE_OPTIONS='--experimental-vm-modules' npm test
